version: '3.7'
 
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - $HOME/jenkins_home:/var/jenkins_home
    environment:
      - TZ=Asia/Seoul
 
  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: true
    restart: always
    volumes:
      - ./jenkins.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Seoul
